name: Kubescape

on:
  push:
    branches: [ main ]
  pull_request:  
    branches: [ main ]

jobs:
  nsa-security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
      
      - name: updating path
        run: export PATH=$PATH:/c/Users/Asus/.kubescape/bin
    
      - name: Scan YAML files checks
        run: kubescape scan framework nsa *.yaml
