name: Kubescape Scan

on:
  push:
    branches:
      - main

jobs:
  nsa-security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

      - name: Add Kubescape to PATH
        run: |
          echo "PATH=\$PATH:$HOME/.kubescape" >> $GITHUB_ENV

      - name: Scan YAML files
        run: |
          export PATH=$PATH:$HOME/.kubescape
          kubescape scan framework nsa *.yaml
