name: Kubescape

on:
  push:
    branches: [ main ]
  pull_request:  
    branches: [ main ]

jobs:
  nsa-security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Kubescape
        run:  curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash

      - name: setting up path
        run: export PATH=$PATH:/home/runner/.kubescape/bin
      
      - name: Scan YAML files
        run: kubescape scan framework nsa *.yaml
